#docker-stack.yml

version: '3.3'

services:

  filebeat:
    image: bigprofiles.azurecr.io/filebeat:latest
    volumes:
      - /data/docker/containers:/usr/share/filebeat/dockerlogs/data
      - /var/run/docker.sock:/var/run/docker.sock
      - filebeat-data:/usr/share/filebeat/data
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      HOSTNAME: ${HOSTNAME}
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    networks:
      - beat
    deploy:
      mode: replicated
      replicas: 1

configs:
  filebeat_config:
    file: ./filebeat.yml

networks:
  beat:
    driver: overlay

volumes:
  filebeat-data:
    external: true