#docker-stack.yml

version: '3.3'

services:

  filebeat:
    image: filebeat-root:latest
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    networks:
      - beat
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /data/docker/containers:/usr/share/filebeat/dockerlogs/data
      - /var/run/docker.sock:/var/run/docker.sock
      - filebeat-data:/usr/share/filebeat/data

configs:
  filebeat_config:
    file: ./config/filebeat.yml

networks:
  beat:
    driver: overlay

volumes:
  filebeat-data:
    external: true
